name: 'Generate Daily Report'

on:
  schedule:
    - cron: 6 * * * *    
  workflow_dispatch:
  
permissions:
  issues: read
  contents: write

jobs:
  report:
    runs-on: ubuntu-18.04
    timeout-minutes: 10
    steps:
      - id: report
        uses: gramster/github-issue-reporter@main
        with:
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          branch: reports
          team: '+fabioz,luabud,ijoosong,heejaechang,zooba,brettcannon,kieferrm,ronglums,DonJayamanne,kimadeline,int19h,gramster,qubitron,rchiodo,greazer,ericsnowcurrently,judej,paulacamargo25,bschnurr,karthiknadig,JoshuaPartlow,AdamYoblick,karrtikr,StellaHuang95'
        
