variables:
    architecture: "x64"
    python.version: "3.8"

jobs:
    - job: 'Coverage'
      timeoutInMinutes: 15
      pool:
          name: Azure Pipelines
          demands: java
          vmImage: "ubuntu-16.04"
      steps:
        - template: "templates/coverage.yml"